### ISSUE TITLE
Calling your stuff "better" and then proceeds to DDOS

### ISSUE THREAD

**Issue by SMJSGaming** [foxodever/BetterCvoltonGDPS#4]
Just so you know, Cvolton, Rya (owner of the free hosting service) and I are well aware that you've tried to DDOS us.

**Comment by SMJSGaming** [comment]
Like holy hell can you be more obvious???

![image](https://user-images.githubusercontent.com/38814077/131499835-a9352c72-d451-4d47-8602-4bd600498e5a.png)

**Comment by foxodever** [comment]
Bro. Russain location doesn't mean what I AM DDOSED.
I ddosed fhgdps before but now i developing my fucking website.
Russia doesn't mean me, not only me ddosed fhgdps in Russia
Please if you wanna talk about it, contact me on discord: Foxodever#8618 but not here.
Thank you.

**Comment by SMJSGaming** [comment]
Doesn't help that you tried to flex it on tiktok

![image](https://user-images.githubusercontent.com/38814077/131506713-cc749135-7d94-4c55-bd2d-71148e8f4038.png)

**Comment by masckmaster2007** [comment]
@SMJSGaming send link

**Comment by masckmaster2007** [comment]
<h1>f
