### ISSUE TITLE
Not working register account. 

### ISSUE THREAD

**Issue by DiegoArmando-27** [foxodever/BetterCvoltonGDPS#57]
Hi foxodever. 
I installed your cernel. Server is working. 
But i can't register my account. 
How to fix it? 
At least, your support link is not working too.

**Comment by foxodever** [comment]
Hello. Yea i forgot change link, try https://discord.gg/8bzEcShgpe

About register. Make sure you setup `/config/mail.php` propertly. Try use https://reqbin.com/post-online to send post request and check what server is returning. If server returns just `-1` when you send right post data, that means you setuped `mail.php` not correct. 

(Sorry for bad English)

**Comment by DiegoArmando-27** [comment]
> Hello. Yea i forgot change link, try https://discord.gg/8bzEcShgpe
> 
> About register. Make sure you setup `/config/mail.php` propertly. Try use https://reqbin.com/post-online to send post request and check what server is returning. If server returns just `-1` when you send right post data, that means you setuped `mail.php` not correct.
> 
> (Sorry for bad English)

thank you.
