### ISSUE TITLE
mail.php

### ISSUE THREAD

**Issue by DiegoArmando-27** [foxodever/BetterCvoltonGDPS#58]
Hi foxodever (again) 
I have a question. How to setup a mail.php file?

**Comment by foxodever** [comment]
> Hi foxodever (again) I have a question. How to setup a mail.php file?

You need smtp server and mail on it. You can use google smtp. https://support.google.com/mail/answer/7126229

**Comment by DiegoArmando-27** [comment]
> > Hi foxodever (again) I have a question. How to setup a mail.php file?
> 
> You need smtp server and mail on it. You can use google smtp. https://support.google.com/mail/answer/7126229

not working. I have configured all the files, but still writes Something went wrong

**Comment by foxodever** [comment]
> > > Hi foxodever (again) I have a question. How to setup a mail.php file?
> > 
> > 
> > You need smtp server and mail on it. You can use google smtp. https://support.google.com/mail/answer/7126229
> 
> not working. I have configured all the files, but still writes Something went wrong

Make sure you enabled everything in gmail account setting if you use gmail smtp. Also if you use gmail make sure you changed ssl to tls and change port 456 to 587 in mail.php

**Comment by DiegoArmando-27** [comment]
> > > > Hi foxodever (again) I have a question. How to setup a mail.php file?
> > > 
> > > 
> > > You need smtp server and mail on it. You can use google smtp. https://support.google.com/mail/answer/7126229
> > 
> > 
> > not working. I have configured all the files, but still writes Something went wrong
> 
> Make sure you enabled everything in gmail account setting if you use gmail smtp. Also if you use gmail make sure you changed ssl to tls and change port 456 to 587 in mail.php

Writing:
Connection failed: SQLSTATE[HY000] [2006] MySQL server has gone away
(host is working)

**Comment by foxodever** [comment]
> > > > > Hi foxodever (again) I have a question. How to setup a mail.php file?
> > > > 
> > > > 
> > > > You need smtp server and mail on it. You can use google smtp. https://support.google.com/mail/answer/7126229
> > > 
> > > 
> > > not working. I have configured all the files, but still writes Something went wrong
> > 
> > 
> > Make sure you enabled everything in gmail account setting if you use gmail smtp. Also if you use gmail make sure you changed ssl to tls and change port 456 to 587 in mail.php
> 
> Writing: Connection failed: SQLSTATE[HY000] [2006] MySQL server has gone away (host is working)

Not mine problem, make sure you set hostname corectly, contact hosting support for more info

**Comment by DiegoArmando-27** [comment]
> > > > > > Hi foxodever (again) I have a question. How to setup a mail.php file?
> > > > > 
> > > > > 
> > > > > You need smtp server and mail on it. You can use google smtp. https://support.google.com/mail/answer/7126229
> > > > 
> > > > 
> > > > not working. I have configured all the files, but still writes Something went wrong
> > > 
> > > 
> > > Make sure you enabled everything in gmail account setting if you use gmail smtp. Also if you use gmail make sure you changed ssl to tls and change port 456 to 587 in mail.php
> > 
> > 
> > Writing: Connection failed: SQLSTATE[HY000] [2006] MySQL server has gone away (host is working)
> 
> Not mine problem, make sure you set hostname corectly, contact hosting support for more info

Okay, i solved this problem with servers and they are working.
But account register is not working
You can see how working registerGJaccount.php in screenshot
![image](https://user-images.githubusercontent.com/73876067/144360635-c32676cf-ae02-47e9-8e39-5ab25ba00833.png)

**Comment by IronGoldOfficial** [comment]
Hi! I configured all the files, but account register doesn't working. Help me please)

**Comment by DiegoArmando-27** [comment]
> Hi! I configured all the files, but account register doesn't working. Help me please)

i have a some problem

**Comment by foxodever** [comment]
PLEASE CONTACT YOUR HOSTING PROVIDER AND ASK ABOUT MAIL SMTP SERVER.
JUST GOOGLE AND LAERN WHAT IS SMTP.
