### ISSUE TITLE
Seems like the limit for song uploading is 2mb, not 8mb

### ISSUE THREAD

**Issue by masckmaster2007** [foxodever/BetterCvoltonGDPS#62]
Whenever i try, it refreshes the page without any errors or giving me a ID
https://dgdps.ix.tc/database/tools/songs/upload.php
test it here

**Comment by foxodever** [comment]
Just uploaded song, everything is fine
![image](https://user-images.githubusercontent.com/52624723/177042455-1ae7f97b-5552-410c-a5e4-8c0ab11463cb.png)
If you try to refresh the page AFTER loading, then it's because the browser sends the file again
