### ISSUE TITLE
HTTPS support ?

### ISSUE THREAD

**Issue by masckmaster2007** [foxodever/BetterCvoltonGDPS#63]
Hey. So i need to know if HTTPS is supported. Absolute did it sort-of on his 1.9 GDPS, and for me privacy and security is my priority. Help

**Comment by foxodever** [comment]
HTTPS supported

**Comment by masckmaster2007** [comment]
how i do this.
it's broken i think. gonna check

**Comment by masckmaster2007** [comment]
**It actually works**
