### ISSUE TITLE
Hashing "hostname"

### ISSUE THREAD

**Issue by masckmaster2007** [foxodever/BetterCvoltonGDPS#64]
In "levels" table, add a hashing algorithm for "hostname" instead of putting ip addresses in plain text

Idk if this can lead to other problems such as hackers' ip not being shown for banning them...

**Comment by foxodever** [comment]
If a Hacker hacks the database, the IP won't give him anything. Especially if it is dynamic. But even if it is not dynamic, the IP will not give anything. Maximum country and region of player

**Comment by masckmaster2007** [comment]
Yes i know that, but i don't really want to see that kind of info 🙃
